name: sci_space_x
description: A new Flutter project.

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.6
  flutter_spinkit: ^5.2.0
  provider: ^6.0.5
  animated_text_kit: ^4.2.2
  google_fonts: ^4.0.4
  shared_preferences: ^2.1.1
  firebase_core: ^2.12.0
  firebase_auth: ^4.6.0
  google_sign_in: ^6.1.0
  kf_drawer: ^1.2.1
  get: ^4.6.5
  get_it: ^7.6.0
  flutter_staggered_grid_view: ^0.6.2
  shimmer: ^2.0.0
  cached_network_image: ^3.2.3
  path_provider: ^2.0.15
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.13.1
  # gallery_saver: ^2.3.2
  # image_picker_saver: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
